version: 1.0
name: babyalpaca
download_urls: https://raw.githubusercontent.com/roshanis/ludwig/master/ludwig/datasets/babyalpaca.json
dataset_filenames: babyalpaca.json
description: |
  Baby Alpaca instruction-tuning dataset for LLM fine-tuning.
columns:
  - name: instruction
    type: text
  - name: input
    type: text
  - name: output
    type: text
output_features:
  - name: output
    type: text
